### PR TITLE
feat: support tailwind config in typescript

### LINKED ISSUE #228: [BUG] Support tailwind.config.ts
**Describe the bug**
Tailwind release v3.3 today [introduced support](https://tailwindcss.com/blog/tailwindcss-v3-3) for ESM and TypeScript config files. It currently does not look like the ESLint plugin supports configuration files written in `tailwind.config.ts`. 

**To Reproduce**
1. Follow the demo instructions in the v3.3 release blog post and set up a TypeScript configuration. 
2. Run eslint
3. The configuration file is not loaded in, causing false positives. 

**Expected behavior**
Config files written with `tailwind.config.ts` should be supported. 

**Environment (please complete the following information):**
- Tailwind v3.3
- ESLint v8.36.0
- Plugin: v3.10.1

**Additional context**
This may be a duplicate of #156, but it is introduced with a different context. Escalated it to bug because there is now official support for config files written in TypeScript. 

**Related upstream PR**
https://github.com/tailwindlabs/tailwindcss/pull/10785

### PR DESCRIPTION
**Pull request by quesabe**
# Support tailwind config written in typescript as well as other common extensions

## Description

- Replace simple `require` on tailwind config with the `loadConfig` function from _tailwindcss_ package that supports typescript parsing
- Switch from hardcoded name for default config to `resolveDefaultConfigPath` function from _tailwindcss_ package that looks for one of `./tailwind.config.{js,cjs,mjs,ts}`
- Update _tailwindcss_ to v3.3.x in order to import the new functionality from the package
- Because of update beyond v3.3.0 an additional fixes were made for classnames-order rule tests since[ tailwindcss changed the ordering function at v3.3.0](https://github.com/tailwindlabs/tailwindcss/pull/10672).

Fixes #228

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

In a any project with _tailwindcss_ and _eslint-plugin-tailwindcss_ that utilises a JS-based config:
- define some custom theme in the config (I used `theme: {colors: {blueish: `#0000aa`}}`;
- use a class based on the custom theme (`text-blueish` in my case);
- ensure the rule does not work (`no-custom-classname` in my case);
- rename config to `ts` extension;
- add typings so that the file is not parsable by a JS engine;
- check that the rule reports the custom class (evidently because config is not loaded);
- switch the _eslint-plugin-tailwindcss_ in `package.json` to the local repo checked out from this branch;
- now the custom config shall be loaded correctly and the rule again does not report.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by francoismassart** [comment]
👋 @quesabe 
Thank you for contributing, 🙏  
I just published your PR in the beta channel

`npm i eslint-plugin-tailwindcss@3.12.0-beta.0`

I'll run it against my current project for a last test prior to release.

**Comment by francoismassart** [comment]
Looking good except that I had to update my project's dependency to:

`tailwindcss@3.3.2`

I'm planning to release it this monday, if some users of the plugin want to try the beta version and provide feedback and it would be appreciated as well.

Cheers

**Comment by getinnocuous** [comment]
I've tested this out and it works fine for me! Below are all of my tailwind related dependencies

```
"tailwind-merge": "^1.12.0",
"tailwindcss": "^3.3.1",
"tailwindcss-animate": "^1.0.5",
"tailwindcss-radix": "^2.8.0",
"@tailwindcss/forms": "^0.5.3",
"eslint-plugin-tailwindcss": "^3.12.0-beta.0",
"prettier-plugin-tailwindcss": "^0.2.7",
```

**Comment by pm0u** [comment]
Also seems to be working properly for me IDE & CLI, alongside prettier as well.

```
    "eslint": "8.28.0",
    "eslint-config-next": "13.1.2",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard-with-typescript": "^24.0.0",
    "eslint-mdx": "^2.0.5",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-mdx": "^2.0.5",
    "eslint-plugin-n": "^15.6.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-storybook": "^0.6.8",
    "eslint-plugin-tailwindcss": "3.12.0-beta.0",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "tailwindcss": "^3.3.2",
```

**Comment by itsmingjie** [comment]
Thanks, @quesabe!

**Pull request merged**
