### PR TITLE
feat: include class names from `.css` as valid custom classes

### LINKED ISSUE #24: [Feature request] Include class names from .css as valid custom classes
**Is your feature request related to a problem? Please describe.**
For every custom class included in a tailwind.css file, It is needed to add them to the whitelist option for the `no-custom-classname` rule. For projects where custom classes are used a lot, this could be hard to keep track off.

```css
/* tailwind.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
    .btn {
        @apply p-4 border rounded
    }
   ...
}

```
**Describe the solution you'd like**
It would be nice if this plugin would include all classes created in the .css file  by default. 
Perhaps in addition to whitelisting specific classes, it could also accept paths for .css files with classes that should be whitelisted.

**Describe alternatives you've considered**
Using the whitelist option for the `no-custom-classname` rule.

### PR DESCRIPTION
**Pull request by francoismassart**
# Pull Request Name

## Description

This PR is processing all `.css` files through `post` and  extracting its classnames in order to accept them as valid.

Fixes #24 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- `npm test`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by francoismassart** [comment]
I'll also add the [`files` parameter](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) to the `package.json`

**Comment by adamlindqvist** [comment]
Did a quick test and looks good to me! 👍

**Comment by thebuilder** [comment]
Looks good - wondering if the caching/loading css strategy can be improved? 
I'm wondering what impact it will have on a project with many css files (but maybe that won't be an issue in your typical Tailwind project)

The 5 second refresh delay works, but seems a bit iffy😄

An option could be to have a cache file, the contains a mapping of all css files with a modified timestamp and the parsed classes. Use `fs.access` to validate if a file exists and has been updated since the last time it was read. 
Just an idea🤔

Is it possible to read files async?

**Comment by francoismassart** [comment]
@thebuilder good idea about the caching 👍 
Reading files async is possible but I don't think eslint-rules support asynchronous code.
I was not able to run the tests successfuly with asynchronous code within the rule...

**Pull request merged**
