### PR TITLE
Fixed regression if lint runs more than cssFilesRefreshRate

### PR DESCRIPTION
**Pull request by XantreDev**
# Pull Request Name

## Description

Tries to fix behavior regression

Fixes https://github.com/francoismassart/eslint-plugin-tailwindcss/pull/338#discussion_r1628453766

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Runed tests
- [ ] Add E2E test that checks lint running more than cssRefreshTime

**Test Configuration**:

- OS + version: e.g. macOS Mojave
- NPM version: ...
- Node version: ...

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by francoismassart** [comment]
@XantreDev,
I've been working on similar issue on this beta release, would you mind trying it in your projects and let me know if everything run smoothly ?

`npm i eslint-plugin-tailwindcss@3.17.3-beta.3 -D`

**Comment by francoismassart** [comment]
Should be fixed in latest release (3.17.4)

**Comment by XantreDev** [comment]
Sorry. Had other things to do
Btw, I've implement e2e test, which checked error with lint on long run and encountered that my version with fix works slower than original one. Probably because of additional stats call. I would like to commit it and add to the tests

**Comment by francoismassart** [comment]
@XantreDev, no worries, contributions are always welcome.

You can simply create a new PR with the suggested changes.

**Pull request closed without merging**
